PATCH  http://bastianschmalbach.ddns.net/tipps/26D0346F-0BC0-4877-9374-3A19CF17F1C1?thumb=up

###

GET http://127.0.0.1:9000/tipps

###

DELETE http://bastianschmalbach.ddns.net/tipps/5f722a4dd2d9541468b12225

###

POST http://bastianschmalbach.ddns.net/users
Content-Type: application/json

{
    "phoneId": "8F02B169-1968-4545-893C-sasadmdas"
}

###

DELETE http://127.0.0.1:9000/reportedtipps/5f79ef23125f5dcd5125c64e

###

PATCH http://127.0.0.1:9000/tipps/5f7238a31f7d3e1cd65ed8ed
Content-Type: application/json

{
    "thumb": "down"
}

###

GET https://sustainablelife.herokuapp.com/feedbacks

###

POST https://sustainablelife.herokuapp.com/feedbacks
Content-Type: application/json

{
    "feedback": "Das hier ist ein Feedback Report",
    "feedbackType": "report",
    "userID": "12312313",
    "userName": "12312313"
}

###

GET https://sustainablelife.herokuapp.com/users/5f7232ae79d17e1977483c3a


###

GET https://sustainablelife.herokuapp.com/tipps?category=Transport
Content-Type: application/json

{
    "maxscore": 20
}

###

DELETE https://sustainablelife.herokuapp.com/tipps/5f86f868790bc90017ae8b3b


###

PATCH https://sustainablelife.herokuapp.com/tipps/5f876525def53a0017813209
Content-Type: application/json

{
    "thumb": "up"
}

###

PATCH http://bastianschmalbach.ddns.net/users/5f7232ae79d17e1977483c3a
Content-Type: application/json

{
    "log": {
        "kilometer": 0,
        "meat": 0,
        "cooked": 0,
        "foodWaste": 0,
        "drinks": 0,
        "shower": 0,
        "binWaste": 0,
        "date": "20.09.20"
    }
}

###

POST https://sustainablelife.herokuapp.com/tipps
Content-Type: application/json

{
    "source":"",
    "category":"Ernährung",
    "level": "Mittel",
    "official":"Community",
    "title":"Test Titel",
    "postedBy":"5f7232ae79d17e1977483c3a"
}

###

POST https://sustainablelife.herokuapp.com/tipps
Content-Type: application/json

{
    "source":"",
    "category":"Haushalt",
    "level": "Einfach",
    "official":"Offiziell",
    "title":"Jaaaa",
    "postedBy":"5f7232ae79d17e1977483c3a"
}

###

POST https://sustainablelife.herokuapp.com/users
Content-Type: application/json

{
    "name": "Sustainable Team 🌱",
    "age": "18-25",
    "phoneId": "MacBook"
}