PATCH  http://bastianschmalbach.ddns.net/tipps/26D0346F-0BC0-4877-9374-3A19CF17F1C1?thumb=up

###

GET http://127.0.0.1:9000/tipps

###

DELETE http://bastianschmalbach.ddns.net/tipps/5f722a4dd2d9541468b12225

###

POST http://bastianschmalbach.ddns.net/users
Content-Type: application/json

{
    "phoneId": "8F02B169-1968-4545-893C-sasadmdas"
}

###

DELETE http://127.0.0.1:9000/reportedtipps/5f79ef23125f5dcd5125c64e

###

PATCH http://127.0.0.1:9000/tipps/5f7238a31f7d3e1cd65ed8ed
Content-Type: application/json

{
    "thumb": "down"
}

###

GET https://sustainablelife.herokuapp.com/feedbacks

###

POST https://sustainablelife.herokuapp.com/feedbacks
Content-Type: application/json

{
    "feedback": "Das hier ist ein Feedback Report",
    "feedbackType": "report",
    "userID": "12312313",
    "userName": "12312313"
}

###

GET https://sustainablelife.herokuapp.com/facts


###

PATCH http://bastianschmalbach.ddns.net/users/5f722dd7d2d9541468b12226
Content-Type: application/json

{
    "checkedTipps": "TippID2"
}

###

PATCH http://bastianschmalbach.ddns.net/users/5f7232ae79d17e1977483c3a
Content-Type: application/json

{
    "log": {
        "kilometer": 0,
        "meat": 0,
        "cooked": 0,
        "foodWaste": 0,
        "drinks": 0,
        "shower": 0,
        "binWaste": 0,
        "date": "20.09.20"
    }
}

###

POST https://sustainablelife.herokuapp.com/facts
Content-Type: application/json

{
    "source":"",
    "category":"Ressourcen",
    "score": 0,
    "official":"Offiziell",
    "title":"Seconnd Hand",
    "level":"Schwer",
    "postedBy":"8F02B169-1968-4545-893C-8AD514886ADD",
    "score": 25
}